// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: proto/sync/v1/sync.proto

package syncv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CollectorFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*CollectorFrame_Hello
	//	*CollectorFrame_Event
	//	*CollectorFrame_ReplayUnavailable
	//	*CollectorFrame_Metrics
	//	*CollectorFrame_Idle
	//	*CollectorFrame_ReconcileResult
	//	*CollectorFrame_RepairAccepted
	//	*CollectorFrame_ResumeAccepted
	Body          isCollectorFrame_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectorFrame) Reset() {
	*x = CollectorFrame{}
	mi := &file_proto_sync_v1_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectorFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectorFrame) ProtoMessage() {}

func (x *CollectorFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_v1_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectorFrame.ProtoReflect.Descriptor instead.
func (*CollectorFrame) Descriptor() ([]byte, []int) {
	return file_proto_sync_v1_sync_proto_rawDescGZIP(), []int{0}
}

func (x *CollectorFrame) GetBody() isCollectorFrame_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *CollectorFrame) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Body.(*CollectorFrame_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *CollectorFrame) GetEvent() *Event {
	if x != nil {
		if x, ok := x.Body.(*CollectorFrame_Event); ok {
			return x.Event
		}
	}
	return nil
}

func (x *CollectorFrame) GetReplayUnavailable() *ReplayUnavailable {
	if x != nil {
		if x, ok := x.Body.(*CollectorFrame_ReplayUnavailable); ok {
			return x.ReplayUnavailable
		}
	}
	return nil
}

func (x *CollectorFrame) GetMetrics() *Metrics {
	if x != nil {
		if x, ok := x.Body.(*CollectorFrame_Metrics); ok {
			return x.Metrics
		}
	}
	return nil
}

func (x *CollectorFrame) GetIdle() *Idle {
	if x != nil {
		if x, ok := x.Body.(*CollectorFrame_Idle); ok {
			return x.Idle
		}
	}
	return nil
}

func (x *CollectorFrame) GetReconcileResult() *ReconcileResult {
	if x != nil {
		if x, ok := x.Body.(*CollectorFrame_ReconcileResult); ok {
			return x.ReconcileResult
		}
	}
	return nil
}

func (x *CollectorFrame) GetRepairAccepted() *RepairAccepted {
	if x != nil {
		if x, ok := x.Body.(*CollectorFrame_RepairAccepted); ok {
			return x.RepairAccepted
		}
	}
	return nil
}

func (x *CollectorFrame) GetResumeAccepted() *ResumeAccepted {
	if x != nil {
		if x, ok := x.Body.(*CollectorFrame_ResumeAccepted); ok {
			return x.ResumeAccepted
		}
	}
	return nil
}

type isCollectorFrame_Body interface {
	isCollectorFrame_Body()
}

type CollectorFrame_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type CollectorFrame_Event struct {
	Event *Event `protobuf:"bytes,2,opt,name=event,proto3,oneof"`
}

type CollectorFrame_ReplayUnavailable struct {
	ReplayUnavailable *ReplayUnavailable `protobuf:"bytes,3,opt,name=replay_unavailable,json=replayUnavailable,proto3,oneof"`
}

type CollectorFrame_Metrics struct {
	Metrics *Metrics `protobuf:"bytes,4,opt,name=metrics,proto3,oneof"`
}

type CollectorFrame_Idle struct {
	Idle *Idle `protobuf:"bytes,5,opt,name=idle,proto3,oneof"`
}

type CollectorFrame_ReconcileResult struct {
	ReconcileResult *ReconcileResult `protobuf:"bytes,6,opt,name=reconcile_result,json=reconcileResult,proto3,oneof"`
}

type CollectorFrame_RepairAccepted struct {
	RepairAccepted *RepairAccepted `protobuf:"bytes,7,opt,name=repair_accepted,json=repairAccepted,proto3,oneof"`
}

type CollectorFrame_ResumeAccepted struct {
	ResumeAccepted *ResumeAccepted `protobuf:"bytes,8,opt,name=resume_accepted,json=resumeAccepted,proto3,oneof"`
}

func (*CollectorFrame_Hello) isCollectorFrame_Body() {}

func (*CollectorFrame_Event) isCollectorFrame_Body() {}

func (*CollectorFrame_ReplayUnavailable) isCollectorFrame_Body() {}

func (*CollectorFrame_Metrics) isCollectorFrame_Body() {}

func (*CollectorFrame_Idle) isCollectorFrame_Body() {}

func (*CollectorFrame_ReconcileResult) isCollectorFrame_Body() {}

func (*CollectorFrame_RepairAccepted) isCollectorFrame_Body() {}

func (*CollectorFrame_ResumeAccepted) isCollectorFrame_Body() {}

type ServerFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*ServerFrame_Pull
	//	*ServerFrame_Ack
	//	*ServerFrame_Reconcile
	//	*ServerFrame_Repair
	//	*ServerFrame_Resume
	Body          isServerFrame_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerFrame) Reset() {
	*x = ServerFrame{}
	mi := &file_proto_sync_v1_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerFrame) ProtoMessage() {}

func (x *ServerFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_v1_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerFrame.ProtoReflect.Descriptor instead.
func (*ServerFrame) Descriptor() ([]byte, []int) {
	return file_proto_sync_v1_sync_proto_rawDescGZIP(), []int{1}
}

func (x *ServerFrame) GetBody() isServerFrame_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ServerFrame) GetPull() *Pull {
	if x != nil {
		if x, ok := x.Body.(*ServerFrame_Pull); ok {
			return x.Pull
		}
	}
	return nil
}

func (x *ServerFrame) GetAck() *Ack {
	if x != nil {
		if x, ok := x.Body.(*ServerFrame_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *ServerFrame) GetReconcile() *ReconcileRequest {
	if x != nil {
		if x, ok := x.Body.(*ServerFrame_Reconcile); ok {
			return x.Reconcile
		}
	}
	return nil
}

func (x *ServerFrame) GetRepair() *RepairRequest {
	if x != nil {
		if x, ok := x.Body.(*ServerFrame_Repair); ok {
			return x.Repair
		}
	}
	return nil
}

func (x *ServerFrame) GetResume() *ResumeRequest {
	if x != nil {
		if x, ok := x.Body.(*ServerFrame_Resume); ok {
			return x.Resume
		}
	}
	return nil
}

type isServerFrame_Body interface {
	isServerFrame_Body()
}

type ServerFrame_Pull struct {
	Pull *Pull `protobuf:"bytes,1,opt,name=pull,proto3,oneof"`
}

type ServerFrame_Ack struct {
	Ack *Ack `protobuf:"bytes,2,opt,name=ack,proto3,oneof"`
}

type ServerFrame_Reconcile struct {
	Reconcile *ReconcileRequest `protobuf:"bytes,3,opt,name=reconcile,proto3,oneof"`
}

type ServerFrame_Repair struct {
	Repair *RepairRequest `protobuf:"bytes,4,opt,name=repair,proto3,oneof"`
}

type ServerFrame_Resume struct {
	Resume *ResumeRequest `protobuf:"bytes,5,opt,name=resume,proto3,oneof"`
}

func (*ServerFrame_Pull) isServerFrame_Body() {}

func (*ServerFrame_Ack) isServerFrame_Body() {}

func (*ServerFrame_Reconcile) isServerFrame_Body() {}

func (*ServerFrame_Repair) isServerFrame_Body() {}

func (*ServerFrame_Resume) isServerFrame_Body() {}

type Hello struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SyncerId           string                 `protobuf:"bytes,1,opt,name=syncer_id,json=syncerId,proto3" json:"syncer_id,omitempty"`
	Generation         string                 `protobuf:"bytes,2,opt,name=generation,proto3" json:"generation,omitempty"`
	EarliestSeq        uint64                 `protobuf:"varint,3,opt,name=earliest_seq,json=earliestSeq,proto3" json:"earliest_seq,omitempty"`
	ReadySeq           uint64                 `protobuf:"varint,4,opt,name=ready_seq,json=readySeq,proto3" json:"ready_seq,omitempty"`
	ProtocolVersion    string                 `protobuf:"bytes,5,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	ReconcileSupported bool                   `protobuf:"varint,6,opt,name=reconcile_supported,json=reconcileSupported,proto3" json:"reconcile_supported,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_proto_sync_v1_sync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_v1_sync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_proto_sync_v1_sync_proto_rawDescGZIP(), []int{2}
}

func (x *Hello) GetSyncerId() string {
	if x != nil {
		return x.SyncerId
	}
	return ""
}

func (x *Hello) GetGeneration() string {
	if x != nil {
		return x.Generation
	}
	return ""
}

func (x *Hello) GetEarliestSeq() uint64 {
	if x != nil {
		return x.EarliestSeq
	}
	return 0
}

func (x *Hello) GetReadySeq() uint64 {
	if x != nil {
		return x.ReadySeq
	}
	return 0
}

func (x *Hello) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *Hello) GetReconcileSupported() bool {
	if x != nil {
		return x.ReconcileSupported
	}
	return false
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Json          []byte                 `protobuf:"bytes,3,opt,name=json,proto3" json:"json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_proto_sync_v1_sync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_v1_sync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_proto_sync_v1_sync_proto_rawDescGZIP(), []int{3}
}

func (x *Event) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Event) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *Event) GetJson() []byte {
	if x != nil {
		return x.Json
	}
	return nil
}

type ReplayUnavailable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestedSeq  uint64                 `protobuf:"varint,1,opt,name=requested_seq,json=requestedSeq,proto3" json:"requested_seq,omitempty"`
	EarliestSeq   uint64                 `protobuf:"varint,2,opt,name=earliest_seq,json=earliestSeq,proto3" json:"earliest_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplayUnavailable) Reset() {
	*x = ReplayUnavailable{}
	mi := &file_proto_sync_v1_sync_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayUnavailable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayUnavailable) ProtoMessage() {}

func (x *ReplayUnavailable) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_v1_sync_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayUnavailable.ProtoReflect.Descriptor instead.
func (*ReplayUnavailable) Descriptor() ([]byte, []int) {
	return file_proto_sync_v1_sync_proto_rawDescGZIP(), []int{4}
}

func (x *ReplayUnavailable) GetRequestedSeq() uint64 {
	if x != nil {
		return x.RequestedSeq
	}
	return 0
}

func (x *ReplayUnavailable) GetEarliestSeq() uint64 {
	if x != nil {
		return x.EarliestSeq
	}
	return 0
}

type Idle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReadySeq      uint64                 `protobuf:"varint,1,opt,name=ready_seq,json=readySeq,proto3" json:"ready_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Idle) Reset() {
	*x = Idle{}
	mi := &file_proto_sync_v1_sync_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Idle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Idle) ProtoMessage() {}

func (x *Idle) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_v1_sync_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Idle.ProtoReflect.Descriptor instead.
func (*Idle) Descriptor() ([]byte, []int) {
	return file_proto_sync_v1_sync_proto_rawDescGZIP(), []int{5}
}

func (x *Idle) GetReadySeq() uint64 {
	if x != nil {
		return x.ReadySeq
	}
	return 0
}

type Pull struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Generation    string                 `protobuf:"bytes,1,opt,name=generation,proto3" json:"generation,omitempty"`
	Seq           uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pull) Reset() {
	*x = Pull{}
	mi := &file_proto_sync_v1_sync_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pull) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pull) ProtoMessage() {}

func (x *Pull) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_v1_sync_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pull.ProtoReflect.Descriptor instead.
func (*Pull) Descriptor() ([]byte, []int) {
	return file_proto_sync_v1_sync_proto_rawDescGZIP(), []int{6}
}

func (x *Pull) GetGeneration() string {
	if x != nil {
		return x.Generation
	}
	return ""
}

func (x *Pull) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Generation    string                 `protobuf:"bytes,1,opt,name=generation,proto3" json:"generation,omitempty"`
	Seq           uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	MessageId     string                 `protobuf:"bytes,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_proto_sync_v1_sync_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_v1_sync_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_proto_sync_v1_sync_proto_rawDescGZIP(), []int{7}
}

func (x *Ack) GetGeneration() string {
	if x != nil {
		return x.Generation
	}
	return ""
}

func (x *Ack) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Ack) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type ReconcileRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestId      string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	SourceSchema   string                 `protobuf:"bytes,2,opt,name=source_schema,json=sourceSchema,proto3" json:"source_schema,omitempty"`
	Table          string                 `protobuf:"bytes,3,opt,name=table,proto3" json:"table,omitempty"`
	Buckets        uint32                 `protobuf:"varint,4,opt,name=buckets,proto3" json:"buckets,omitempty"`
	AllBuckets     bool                   `protobuf:"varint,5,opt,name=all_buckets,json=allBuckets,proto3" json:"all_buckets,omitempty"`
	Bucket         uint32                 `protobuf:"varint,6,opt,name=bucket,proto3" json:"bucket,omitempty"`
	IncludeRows    bool                   `protobuf:"varint,7,opt,name=include_rows,json=includeRows,proto3" json:"include_rows,omitempty"`
	TimeoutSeconds uint32                 `protobuf:"varint,8,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReconcileRequest) Reset() {
	*x = ReconcileRequest{}
	mi := &file_proto_sync_v1_sync_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconcileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconcileRequest) ProtoMessage() {}

func (x *ReconcileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_v1_sync_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconcileRequest.ProtoReflect.Descriptor instead.
func (*ReconcileRequest) Descriptor() ([]byte, []int) {
	return file_proto_sync_v1_sync_proto_rawDescGZIP(), []int{8}
}

func (x *ReconcileRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ReconcileRequest) GetSourceSchema() string {
	if x != nil {
		return x.SourceSchema
	}
	return ""
}

func (x *ReconcileRequest) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *ReconcileRequest) GetBuckets() uint32 {
	if x != nil {
		return x.Buckets
	}
	return 0
}

func (x *ReconcileRequest) GetAllBuckets() bool {
	if x != nil {
		return x.AllBuckets
	}
	return false
}

func (x *ReconcileRequest) GetBucket() uint32 {
	if x != nil {
		return x.Bucket
	}
	return 0
}

func (x *ReconcileRequest) GetIncludeRows() bool {
	if x != nil {
		return x.IncludeRows
	}
	return false
}

func (x *ReconcileRequest) GetTimeoutSeconds() uint32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type BucketDigest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bucket        uint32                 `protobuf:"varint,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Rows          uint64                 `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	Digest        string                 `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BucketDigest) Reset() {
	*x = BucketDigest{}
	mi := &file_proto_sync_v1_sync_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BucketDigest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BucketDigest) ProtoMessage() {}

func (x *BucketDigest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_v1_sync_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BucketDigest.ProtoReflect.Descriptor instead.
func (*BucketDigest) Descriptor() ([]byte, []int) {
	return file_proto_sync_v1_sync_proto_rawDescGZIP(), []int{9}
}

func (x *BucketDigest) GetBucket() uint32 {
	if x != nil {
		return x.Bucket
	}
	return 0
}

func (x *BucketDigest) GetRows() uint64 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *BucketDigest) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

type ReconcileResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	SourceSchema  string                 `protobuf:"bytes,2,opt,name=source_schema,json=sourceSchema,proto3" json:"source_schema,omitempty"`
	Table         string                 `protobuf:"bytes,3,opt,name=table,proto3" json:"table,omitempty"`
	Columns       []string               `protobuf:"bytes,4,rep,name=columns,proto3" json:"columns,omitempty"`
	PrimaryKeys   []string               `protobuf:"bytes,5,rep,name=primary_keys,json=primaryKeys,proto3" json:"primary_keys,omitempty"`
	Digests       []*BucketDigest        `protobuf:"bytes,6,rep,name=digests,proto3" json:"digests,omitempty"`
	RowsJson      []byte                 `protobuf:"bytes,7,opt,name=rows_json,json=rowsJson,proto3" json:"rows_json,omitempty"`
	Error         string                 `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	ColumnTypes   []string               `protobuf:"bytes,9,rep,name=column_types,json=columnTypes,proto3" json:"column_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconcileResult) Reset() {
	*x = ReconcileResult{}
	mi := &file_proto_sync_v1_sync_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconcileResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconcileResult) ProtoMessage() {}

func (x *ReconcileResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_v1_sync_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconcileResult.ProtoReflect.Descriptor instead.
func (*ReconcileResult) Descriptor() ([]byte, []int) {
	return file_proto_sync_v1_sync_proto_rawDescGZIP(), []int{10}
}

func (x *ReconcileResult) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ReconcileResult) GetSourceSchema() string {
	if x != nil {
		return x.SourceSchema
	}
	return ""
}

func (x *ReconcileResult) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *ReconcileResult) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *ReconcileResult) GetPrimaryKeys() []string {
	if x != nil {
		return x.PrimaryKeys
	}
	return nil
}

func (x *ReconcileResult) GetDigests() []*BucketDigest {
	if x != nil {
		return x.Digests
	}
	return nil
}

func (x *ReconcileResult) GetRowsJson() []byte {
	if x != nil {
		return x.RowsJson
	}
	return nil
}

func (x *ReconcileResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ReconcileResult) GetColumnTypes() []string {
	if x != nil {
		return x.ColumnTypes
	}
	return nil
}

type RepairRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepairRequest) Reset() {
	*x = RepairRequest{}
	mi := &file_proto_sync_v1_sync_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepairRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepairRequest) ProtoMessage() {}

func (x *RepairRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_v1_sync_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepairRequest.ProtoReflect.Descriptor instead.
func (*RepairRequest) Descriptor() ([]byte, []int) {
	return file_proto_sync_v1_sync_proto_rawDescGZIP(), []int{11}
}

func (x *RepairRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RepairRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RepairAccepted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepairAccepted) Reset() {
	*x = RepairAccepted{}
	mi := &file_proto_sync_v1_sync_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepairAccepted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepairAccepted) ProtoMessage() {}

func (x *RepairAccepted) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_v1_sync_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepairAccepted.ProtoReflect.Descriptor instead.
func (*RepairAccepted) Descriptor() ([]byte, []int) {
	return file_proto_sync_v1_sync_proto_rawDescGZIP(), []int{12}
}

func (x *RepairAccepted) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type ResumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeRequest) Reset() {
	*x = ResumeRequest{}
	mi := &file_proto_sync_v1_sync_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeRequest) ProtoMessage() {}

func (x *ResumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_v1_sync_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeRequest.ProtoReflect.Descriptor instead.
func (*ResumeRequest) Descriptor() ([]byte, []int) {
	return file_proto_sync_v1_sync_proto_rawDescGZIP(), []int{13}
}

func (x *ResumeRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type ResumeAccepted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeAccepted) Reset() {
	*x = ResumeAccepted{}
	mi := &file_proto_sync_v1_sync_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeAccepted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeAccepted) ProtoMessage() {}

func (x *ResumeAccepted) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_v1_sync_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeAccepted.ProtoReflect.Descriptor instead.
func (*ResumeAccepted) Descriptor() ([]byte, []int) {
	return file_proto_sync_v1_sync_proto_rawDescGZIP(), []int{14}
}

func (x *ResumeAccepted) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// Metrics contains one Prometheus text exposition snapshot. The server adds
// trusted syncer_id and component labels before forwarding it.
type Metrics struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	PrometheusText       []byte                 `protobuf:"bytes,1,opt,name=prometheus_text,json=prometheusText,proto3" json:"prometheus_text,omitempty"`
	CollectedAtUnixMilli int64                  `protobuf:"varint,2,opt,name=collected_at_unix_milli,json=collectedAtUnixMilli,proto3" json:"collected_at_unix_milli,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Metrics) Reset() {
	*x = Metrics{}
	mi := &file_proto_sync_v1_sync_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metrics) ProtoMessage() {}

func (x *Metrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_v1_sync_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metrics.ProtoReflect.Descriptor instead.
func (*Metrics) Descriptor() ([]byte, []int) {
	return file_proto_sync_v1_sync_proto_rawDescGZIP(), []int{15}
}

func (x *Metrics) GetPrometheusText() []byte {
	if x != nil {
		return x.PrometheusText
	}
	return nil
}

func (x *Metrics) GetCollectedAtUnixMilli() int64 {
	if x != nil {
		return x.CollectedAtUnixMilli
	}
	return 0
}

type ListSyncersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSyncersRequest) Reset() {
	*x = ListSyncersRequest{}
	mi := &file_proto_sync_v1_sync_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSyncersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSyncersRequest) ProtoMessage() {}

func (x *ListSyncersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_v1_sync_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSyncersRequest.ProtoReflect.Descriptor instead.
func (*ListSyncersRequest) Descriptor() ([]byte, []int) {
	return file_proto_sync_v1_sync_proto_rawDescGZIP(), []int{16}
}

type SyncerStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Connected     bool                   `protobuf:"varint,2,opt,name=connected,proto3" json:"connected,omitempty"`
	Generation    string                 `protobuf:"bytes,3,opt,name=generation,proto3" json:"generation,omitempty"`
	ReceivedSeq   uint64                 `protobuf:"varint,4,opt,name=received_seq,json=receivedSeq,proto3" json:"received_seq,omitempty"`
	AppliedSeq    uint64                 `protobuf:"varint,5,opt,name=applied_seq,json=appliedSeq,proto3" json:"applied_seq,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncerStatus) Reset() {
	*x = SyncerStatus{}
	mi := &file_proto_sync_v1_sync_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncerStatus) ProtoMessage() {}

func (x *SyncerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_v1_sync_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncerStatus.ProtoReflect.Descriptor instead.
func (*SyncerStatus) Descriptor() ([]byte, []int) {
	return file_proto_sync_v1_sync_proto_rawDescGZIP(), []int{17}
}

func (x *SyncerStatus) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SyncerStatus) GetConnected() bool {
	if x != nil {
		return x.Connected
	}
	return false
}

func (x *SyncerStatus) GetGeneration() string {
	if x != nil {
		return x.Generation
	}
	return ""
}

func (x *SyncerStatus) GetReceivedSeq() uint64 {
	if x != nil {
		return x.ReceivedSeq
	}
	return 0
}

func (x *SyncerStatus) GetAppliedSeq() uint64 {
	if x != nil {
		return x.AppliedSeq
	}
	return 0
}

func (x *SyncerStatus) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ListSyncersResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Syncers         []*SyncerStatus        `protobuf:"bytes,1,rep,name=syncers,proto3" json:"syncers,omitempty"`
	ConfigHash      string                 `protobuf:"bytes,2,opt,name=config_hash,json=configHash,proto3" json:"config_hash,omitempty"`
	LastReloadError string                 `protobuf:"bytes,3,opt,name=last_reload_error,json=lastReloadError,proto3" json:"last_reload_error,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListSyncersResponse) Reset() {
	*x = ListSyncersResponse{}
	mi := &file_proto_sync_v1_sync_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSyncersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSyncersResponse) ProtoMessage() {}

func (x *ListSyncersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_v1_sync_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSyncersResponse.ProtoReflect.Descriptor instead.
func (*ListSyncersResponse) Descriptor() ([]byte, []int) {
	return file_proto_sync_v1_sync_proto_rawDescGZIP(), []int{18}
}

func (x *ListSyncersResponse) GetSyncers() []*SyncerStatus {
	if x != nil {
		return x.Syncers
	}
	return nil
}

func (x *ListSyncersResponse) GetConfigHash() string {
	if x != nil {
		return x.ConfigHash
	}
	return ""
}

func (x *ListSyncersResponse) GetLastReloadError() string {
	if x != nil {
		return x.LastReloadError
	}
	return ""
}

type ReloadConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadConfigRequest) Reset() {
	*x = ReloadConfigRequest{}
	mi := &file_proto_sync_v1_sync_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadConfigRequest) ProtoMessage() {}

func (x *ReloadConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_v1_sync_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadConfigRequest.ProtoReflect.Descriptor instead.
func (*ReloadConfigRequest) Descriptor() ([]byte, []int) {
	return file_proto_sync_v1_sync_proto_rawDescGZIP(), []int{19}
}

type ReloadConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigHash    string                 `protobuf:"bytes,1,opt,name=config_hash,json=configHash,proto3" json:"config_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadConfigResponse) Reset() {
	*x = ReloadConfigResponse{}
	mi := &file_proto_sync_v1_sync_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadConfigResponse) ProtoMessage() {}

func (x *ReloadConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_v1_sync_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadConfigResponse.ProtoReflect.Descriptor instead.
func (*ReloadConfigResponse) Descriptor() ([]byte, []int) {
	return file_proto_sync_v1_sync_proto_rawDescGZIP(), []int{20}
}

func (x *ReloadConfigResponse) GetConfigHash() string {
	if x != nil {
		return x.ConfigHash
	}
	return ""
}

var File_proto_sync_v1_sync_proto protoreflect.FileDescriptor

const file_proto_sync_v1_sync_proto_rawDesc = "" +
	"\n" +
	"\x18proto/sync/v1/sync.proto\x12\tgosync.v1\"\xe7\x03\n" +
	"\x0eCollectorFrame\x12(\n" +
	"\x05hello\x18\x01 \x01(\v2\x10.gosync.v1.HelloH\x00R\x05hello\x12(\n" +
	"\x05event\x18\x02 \x01(\v2\x10.gosync.v1.EventH\x00R\x05event\x12M\n" +
	"\x12replay_unavailable\x18\x03 \x01(\v2\x1c.gosync.v1.ReplayUnavailableH\x00R\x11replayUnavailable\x12.\n" +
	"\ametrics\x18\x04 \x01(\v2\x12.gosync.v1.MetricsH\x00R\ametrics\x12%\n" +
	"\x04idle\x18\x05 \x01(\v2\x0f.gosync.v1.IdleH\x00R\x04idle\x12G\n" +
	"\x10reconcile_result\x18\x06 \x01(\v2\x1a.gosync.v1.ReconcileResultH\x00R\x0freconcileResult\x12D\n" +
	"\x0frepair_accepted\x18\a \x01(\v2\x19.gosync.v1.RepairAcceptedH\x00R\x0erepairAccepted\x12D\n" +
	"\x0fresume_accepted\x18\b \x01(\v2\x19.gosync.v1.ResumeAcceptedH\x00R\x0eresumeAcceptedB\x06\n" +
	"\x04body\"\x85\x02\n" +
	"\vServerFrame\x12%\n" +
	"\x04pull\x18\x01 \x01(\v2\x0f.gosync.v1.PullH\x00R\x04pull\x12\"\n" +
	"\x03ack\x18\x02 \x01(\v2\x0e.gosync.v1.AckH\x00R\x03ack\x12;\n" +
	"\treconcile\x18\x03 \x01(\v2\x1b.gosync.v1.ReconcileRequestH\x00R\treconcile\x122\n" +
	"\x06repair\x18\x04 \x01(\v2\x18.gosync.v1.RepairRequestH\x00R\x06repair\x122\n" +
	"\x06resume\x18\x05 \x01(\v2\x18.gosync.v1.ResumeRequestH\x00R\x06resumeB\x06\n" +
	"\x04body\"\xe0\x01\n" +
	"\x05Hello\x12\x1b\n" +
	"\tsyncer_id\x18\x01 \x01(\tR\bsyncerId\x12\x1e\n" +
	"\n" +
	"generation\x18\x02 \x01(\tR\n" +
	"generation\x12!\n" +
	"\fearliest_seq\x18\x03 \x01(\x04R\vearliestSeq\x12\x1b\n" +
	"\tready_seq\x18\x04 \x01(\x04R\breadySeq\x12)\n" +
	"\x10protocol_version\x18\x05 \x01(\tR\x0fprotocolVersion\x12/\n" +
	"\x13reconcile_supported\x18\x06 \x01(\bR\x12reconcileSupported\"L\n" +
	"\x05Event\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12\x12\n" +
	"\x04json\x18\x03 \x01(\fR\x04json\"[\n" +
	"\x11ReplayUnavailable\x12#\n" +
	"\rrequested_seq\x18\x01 \x01(\x04R\frequestedSeq\x12!\n" +
	"\fearliest_seq\x18\x02 \x01(\x04R\vearliestSeq\"#\n" +
	"\x04Idle\x12\x1b\n" +
	"\tready_seq\x18\x01 \x01(\x04R\breadySeq\"8\n" +
	"\x04Pull\x12\x1e\n" +
	"\n" +
	"generation\x18\x01 \x01(\tR\n" +
	"generation\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\"V\n" +
	"\x03Ack\x12\x1e\n" +
	"\n" +
	"generation\x18\x01 \x01(\tR\n" +
	"generation\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\tR\tmessageId\"\x8b\x02\n" +
	"\x10ReconcileRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12#\n" +
	"\rsource_schema\x18\x02 \x01(\tR\fsourceSchema\x12\x14\n" +
	"\x05table\x18\x03 \x01(\tR\x05table\x12\x18\n" +
	"\abuckets\x18\x04 \x01(\rR\abuckets\x12\x1f\n" +
	"\vall_buckets\x18\x05 \x01(\bR\n" +
	"allBuckets\x12\x16\n" +
	"\x06bucket\x18\x06 \x01(\rR\x06bucket\x12!\n" +
	"\finclude_rows\x18\a \x01(\bR\vincludeRows\x12'\n" +
	"\x0ftimeout_seconds\x18\b \x01(\rR\x0etimeoutSeconds\"R\n" +
	"\fBucketDigest\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\rR\x06bucket\x12\x12\n" +
	"\x04rows\x18\x02 \x01(\x04R\x04rows\x12\x16\n" +
	"\x06digest\x18\x03 \x01(\tR\x06digest\"\xb1\x02\n" +
	"\x0fReconcileResult\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12#\n" +
	"\rsource_schema\x18\x02 \x01(\tR\fsourceSchema\x12\x14\n" +
	"\x05table\x18\x03 \x01(\tR\x05table\x12\x18\n" +
	"\acolumns\x18\x04 \x03(\tR\acolumns\x12!\n" +
	"\fprimary_keys\x18\x05 \x03(\tR\vprimaryKeys\x121\n" +
	"\adigests\x18\x06 \x03(\v2\x17.gosync.v1.BucketDigestR\adigests\x12\x1b\n" +
	"\trows_json\x18\a \x01(\fR\browsJson\x12\x14\n" +
	"\x05error\x18\b \x01(\tR\x05error\x12!\n" +
	"\fcolumn_types\x18\t \x03(\tR\vcolumnTypes\"F\n" +
	"\rRepairRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"/\n" +
	"\x0eRepairAccepted\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\".\n" +
	"\rResumeRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"/\n" +
	"\x0eResumeAccepted\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"i\n" +
	"\aMetrics\x12'\n" +
	"\x0fprometheus_text\x18\x01 \x01(\fR\x0eprometheusText\x125\n" +
	"\x17collected_at_unix_milli\x18\x02 \x01(\x03R\x14collectedAtUnixMilli\"\x14\n" +
	"\x12ListSyncersRequest\"\xb6\x01\n" +
	"\fSyncerStatus\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\tconnected\x18\x02 \x01(\bR\tconnected\x12\x1e\n" +
	"\n" +
	"generation\x18\x03 \x01(\tR\n" +
	"generation\x12!\n" +
	"\freceived_seq\x18\x04 \x01(\x04R\vreceivedSeq\x12\x1f\n" +
	"\vapplied_seq\x18\x05 \x01(\x04R\n" +
	"appliedSeq\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"\x95\x01\n" +
	"\x13ListSyncersResponse\x121\n" +
	"\asyncers\x18\x01 \x03(\v2\x17.gosync.v1.SyncerStatusR\asyncers\x12\x1f\n" +
	"\vconfig_hash\x18\x02 \x01(\tR\n" +
	"configHash\x12*\n" +
	"\x11last_reload_error\x18\x03 \x01(\tR\x0flastReloadError\"\x15\n" +
	"\x13ReloadConfigRequest\"7\n" +
	"\x14ReloadConfigResponse\x12\x1f\n" +
	"\vconfig_hash\x18\x01 \x01(\tR\n" +
	"configHash2O\n" +
	"\vReplication\x12@\n" +
	"\aConnect\x12\x19.gosync.v1.CollectorFrame\x1a\x16.gosync.v1.ServerFrame(\x010\x012\xa6\x01\n" +
	"\x05Admin\x12L\n" +
	"\vListSyncers\x12\x1d.gosync.v1.ListSyncersRequest\x1a\x1e.gosync.v1.ListSyncersResponse\x12O\n" +
	"\fReloadConfig\x12\x1e.gosync.v1.ReloadConfigRequest\x1a\x1f.gosync.v1.ReloadConfigResponseB$Z\"go-sync/internal/rpc/syncv1;syncv1b\x06proto3"

var (
	file_proto_sync_v1_sync_proto_rawDescOnce sync.Once
	file_proto_sync_v1_sync_proto_rawDescData []byte
)

func file_proto_sync_v1_sync_proto_rawDescGZIP() []byte {
	file_proto_sync_v1_sync_proto_rawDescOnce.Do(func() {
		file_proto_sync_v1_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sync_v1_sync_proto_rawDesc), len(file_proto_sync_v1_sync_proto_rawDesc)))
	})
	return file_proto_sync_v1_sync_proto_rawDescData
}

var file_proto_sync_v1_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_proto_sync_v1_sync_proto_goTypes = []any{
	(*CollectorFrame)(nil),       // 0: gosync.v1.CollectorFrame
	(*ServerFrame)(nil),          // 1: gosync.v1.ServerFrame
	(*Hello)(nil),                // 2: gosync.v1.Hello
	(*Event)(nil),                // 3: gosync.v1.Event
	(*ReplayUnavailable)(nil),    // 4: gosync.v1.ReplayUnavailable
	(*Idle)(nil),                 // 5: gosync.v1.Idle
	(*Pull)(nil),                 // 6: gosync.v1.Pull
	(*Ack)(nil),                  // 7: gosync.v1.Ack
	(*ReconcileRequest)(nil),     // 8: gosync.v1.ReconcileRequest
	(*BucketDigest)(nil),         // 9: gosync.v1.BucketDigest
	(*ReconcileResult)(nil),      // 10: gosync.v1.ReconcileResult
	(*RepairRequest)(nil),        // 11: gosync.v1.RepairRequest
	(*RepairAccepted)(nil),       // 12: gosync.v1.RepairAccepted
	(*ResumeRequest)(nil),        // 13: gosync.v1.ResumeRequest
	(*ResumeAccepted)(nil),       // 14: gosync.v1.ResumeAccepted
	(*Metrics)(nil),              // 15: gosync.v1.Metrics
	(*ListSyncersRequest)(nil),   // 16: gosync.v1.ListSyncersRequest
	(*SyncerStatus)(nil),         // 17: gosync.v1.SyncerStatus
	(*ListSyncersResponse)(nil),  // 18: gosync.v1.ListSyncersResponse
	(*ReloadConfigRequest)(nil),  // 19: gosync.v1.ReloadConfigRequest
	(*ReloadConfigResponse)(nil), // 20: gosync.v1.ReloadConfigResponse
}
var file_proto_sync_v1_sync_proto_depIdxs = []int32{
	2,  // 0: gosync.v1.CollectorFrame.hello:type_name -> gosync.v1.Hello
	3,  // 1: gosync.v1.CollectorFrame.event:type_name -> gosync.v1.Event
	4,  // 2: gosync.v1.CollectorFrame.replay_unavailable:type_name -> gosync.v1.ReplayUnavailable
	15, // 3: gosync.v1.CollectorFrame.metrics:type_name -> gosync.v1.Metrics
	5,  // 4: gosync.v1.CollectorFrame.idle:type_name -> gosync.v1.Idle
	10, // 5: gosync.v1.CollectorFrame.reconcile_result:type_name -> gosync.v1.ReconcileResult
	12, // 6: gosync.v1.CollectorFrame.repair_accepted:type_name -> gosync.v1.RepairAccepted
	14, // 7: gosync.v1.CollectorFrame.resume_accepted:type_name -> gosync.v1.ResumeAccepted
	6,  // 8: gosync.v1.ServerFrame.pull:type_name -> gosync.v1.Pull
	7,  // 9: gosync.v1.ServerFrame.ack:type_name -> gosync.v1.Ack
	8,  // 10: gosync.v1.ServerFrame.reconcile:type_name -> gosync.v1.ReconcileRequest
	11, // 11: gosync.v1.ServerFrame.repair:type_name -> gosync.v1.RepairRequest
	13, // 12: gosync.v1.ServerFrame.resume:type_name -> gosync.v1.ResumeRequest
	9,  // 13: gosync.v1.ReconcileResult.digests:type_name -> gosync.v1.BucketDigest
	17, // 14: gosync.v1.ListSyncersResponse.syncers:type_name -> gosync.v1.SyncerStatus
	0,  // 15: gosync.v1.Replication.Connect:input_type -> gosync.v1.CollectorFrame
	16, // 16: gosync.v1.Admin.ListSyncers:input_type -> gosync.v1.ListSyncersRequest
	19, // 17: gosync.v1.Admin.ReloadConfig:input_type -> gosync.v1.ReloadConfigRequest
	1,  // 18: gosync.v1.Replication.Connect:output_type -> gosync.v1.ServerFrame
	18, // 19: gosync.v1.Admin.ListSyncers:output_type -> gosync.v1.ListSyncersResponse
	20, // 20: gosync.v1.Admin.ReloadConfig:output_type -> gosync.v1.ReloadConfigResponse
	18, // [18:21] is the sub-list for method output_type
	15, // [15:18] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_proto_sync_v1_sync_proto_init() }
func file_proto_sync_v1_sync_proto_init() {
	if File_proto_sync_v1_sync_proto != nil {
		return
	}
	file_proto_sync_v1_sync_proto_msgTypes[0].OneofWrappers = []any{
		(*CollectorFrame_Hello)(nil),
		(*CollectorFrame_Event)(nil),
		(*CollectorFrame_ReplayUnavailable)(nil),
		(*CollectorFrame_Metrics)(nil),
		(*CollectorFrame_Idle)(nil),
		(*CollectorFrame_ReconcileResult)(nil),
		(*CollectorFrame_RepairAccepted)(nil),
		(*CollectorFrame_ResumeAccepted)(nil),
	}
	file_proto_sync_v1_sync_proto_msgTypes[1].OneofWrappers = []any{
		(*ServerFrame_Pull)(nil),
		(*ServerFrame_Ack)(nil),
		(*ServerFrame_Reconcile)(nil),
		(*ServerFrame_Repair)(nil),
		(*ServerFrame_Resume)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sync_v1_sync_proto_rawDesc), len(file_proto_sync_v1_sync_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_sync_v1_sync_proto_goTypes,
		DependencyIndexes: file_proto_sync_v1_sync_proto_depIdxs,
		MessageInfos:      file_proto_sync_v1_sync_proto_msgTypes,
	}.Build()
	File_proto_sync_v1_sync_proto = out.File
	file_proto_sync_v1_sync_proto_goTypes = nil
	file_proto_sync_v1_sync_proto_depIdxs = nil
}
