// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: proto/sync/v1/sync.proto

package syncv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CollectorFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*CollectorFrame_Hello
	//	*CollectorFrame_Event
	//	*CollectorFrame_ReplayUnavailable
	//	*CollectorFrame_Metrics
	//	*CollectorFrame_Idle
	Body          isCollectorFrame_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectorFrame) Reset() {
	*x = CollectorFrame{}
	mi := &file_proto_sync_v1_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectorFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectorFrame) ProtoMessage() {}

func (x *CollectorFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_v1_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectorFrame.ProtoReflect.Descriptor instead.
func (*CollectorFrame) Descriptor() ([]byte, []int) {
	return file_proto_sync_v1_sync_proto_rawDescGZIP(), []int{0}
}

func (x *CollectorFrame) GetBody() isCollectorFrame_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *CollectorFrame) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Body.(*CollectorFrame_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *CollectorFrame) GetEvent() *Event {
	if x != nil {
		if x, ok := x.Body.(*CollectorFrame_Event); ok {
			return x.Event
		}
	}
	return nil
}

func (x *CollectorFrame) GetReplayUnavailable() *ReplayUnavailable {
	if x != nil {
		if x, ok := x.Body.(*CollectorFrame_ReplayUnavailable); ok {
			return x.ReplayUnavailable
		}
	}
	return nil
}

func (x *CollectorFrame) GetMetrics() *Metrics {
	if x != nil {
		if x, ok := x.Body.(*CollectorFrame_Metrics); ok {
			return x.Metrics
		}
	}
	return nil
}

func (x *CollectorFrame) GetIdle() *Idle {
	if x != nil {
		if x, ok := x.Body.(*CollectorFrame_Idle); ok {
			return x.Idle
		}
	}
	return nil
}

type isCollectorFrame_Body interface {
	isCollectorFrame_Body()
}

type CollectorFrame_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type CollectorFrame_Event struct {
	Event *Event `protobuf:"bytes,2,opt,name=event,proto3,oneof"`
}

type CollectorFrame_ReplayUnavailable struct {
	ReplayUnavailable *ReplayUnavailable `protobuf:"bytes,3,opt,name=replay_unavailable,json=replayUnavailable,proto3,oneof"`
}

type CollectorFrame_Metrics struct {
	Metrics *Metrics `protobuf:"bytes,4,opt,name=metrics,proto3,oneof"`
}

type CollectorFrame_Idle struct {
	Idle *Idle `protobuf:"bytes,5,opt,name=idle,proto3,oneof"`
}

func (*CollectorFrame_Hello) isCollectorFrame_Body() {}

func (*CollectorFrame_Event) isCollectorFrame_Body() {}

func (*CollectorFrame_ReplayUnavailable) isCollectorFrame_Body() {}

func (*CollectorFrame_Metrics) isCollectorFrame_Body() {}

func (*CollectorFrame_Idle) isCollectorFrame_Body() {}

type ServerFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*ServerFrame_Pull
	//	*ServerFrame_Ack
	Body          isServerFrame_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerFrame) Reset() {
	*x = ServerFrame{}
	mi := &file_proto_sync_v1_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerFrame) ProtoMessage() {}

func (x *ServerFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_v1_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerFrame.ProtoReflect.Descriptor instead.
func (*ServerFrame) Descriptor() ([]byte, []int) {
	return file_proto_sync_v1_sync_proto_rawDescGZIP(), []int{1}
}

func (x *ServerFrame) GetBody() isServerFrame_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ServerFrame) GetPull() *Pull {
	if x != nil {
		if x, ok := x.Body.(*ServerFrame_Pull); ok {
			return x.Pull
		}
	}
	return nil
}

func (x *ServerFrame) GetAck() *Ack {
	if x != nil {
		if x, ok := x.Body.(*ServerFrame_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

type isServerFrame_Body interface {
	isServerFrame_Body()
}

type ServerFrame_Pull struct {
	Pull *Pull `protobuf:"bytes,1,opt,name=pull,proto3,oneof"`
}

type ServerFrame_Ack struct {
	Ack *Ack `protobuf:"bytes,2,opt,name=ack,proto3,oneof"`
}

func (*ServerFrame_Pull) isServerFrame_Body() {}

func (*ServerFrame_Ack) isServerFrame_Body() {}

type Hello struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SyncerId        string                 `protobuf:"bytes,1,opt,name=syncer_id,json=syncerId,proto3" json:"syncer_id,omitempty"`
	Generation      string                 `protobuf:"bytes,2,opt,name=generation,proto3" json:"generation,omitempty"`
	EarliestSeq     uint64                 `protobuf:"varint,3,opt,name=earliest_seq,json=earliestSeq,proto3" json:"earliest_seq,omitempty"`
	ReadySeq        uint64                 `protobuf:"varint,4,opt,name=ready_seq,json=readySeq,proto3" json:"ready_seq,omitempty"`
	ProtocolVersion string                 `protobuf:"bytes,5,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_proto_sync_v1_sync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_v1_sync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_proto_sync_v1_sync_proto_rawDescGZIP(), []int{2}
}

func (x *Hello) GetSyncerId() string {
	if x != nil {
		return x.SyncerId
	}
	return ""
}

func (x *Hello) GetGeneration() string {
	if x != nil {
		return x.Generation
	}
	return ""
}

func (x *Hello) GetEarliestSeq() uint64 {
	if x != nil {
		return x.EarliestSeq
	}
	return 0
}

func (x *Hello) GetReadySeq() uint64 {
	if x != nil {
		return x.ReadySeq
	}
	return 0
}

func (x *Hello) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Json          []byte                 `protobuf:"bytes,3,opt,name=json,proto3" json:"json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_proto_sync_v1_sync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_v1_sync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_proto_sync_v1_sync_proto_rawDescGZIP(), []int{3}
}

func (x *Event) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Event) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *Event) GetJson() []byte {
	if x != nil {
		return x.Json
	}
	return nil
}

type ReplayUnavailable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestedSeq  uint64                 `protobuf:"varint,1,opt,name=requested_seq,json=requestedSeq,proto3" json:"requested_seq,omitempty"`
	EarliestSeq   uint64                 `protobuf:"varint,2,opt,name=earliest_seq,json=earliestSeq,proto3" json:"earliest_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplayUnavailable) Reset() {
	*x = ReplayUnavailable{}
	mi := &file_proto_sync_v1_sync_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayUnavailable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayUnavailable) ProtoMessage() {}

func (x *ReplayUnavailable) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_v1_sync_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayUnavailable.ProtoReflect.Descriptor instead.
func (*ReplayUnavailable) Descriptor() ([]byte, []int) {
	return file_proto_sync_v1_sync_proto_rawDescGZIP(), []int{4}
}

func (x *ReplayUnavailable) GetRequestedSeq() uint64 {
	if x != nil {
		return x.RequestedSeq
	}
	return 0
}

func (x *ReplayUnavailable) GetEarliestSeq() uint64 {
	if x != nil {
		return x.EarliestSeq
	}
	return 0
}

type Idle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReadySeq      uint64                 `protobuf:"varint,1,opt,name=ready_seq,json=readySeq,proto3" json:"ready_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Idle) Reset() {
	*x = Idle{}
	mi := &file_proto_sync_v1_sync_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Idle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Idle) ProtoMessage() {}

func (x *Idle) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_v1_sync_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Idle.ProtoReflect.Descriptor instead.
func (*Idle) Descriptor() ([]byte, []int) {
	return file_proto_sync_v1_sync_proto_rawDescGZIP(), []int{5}
}

func (x *Idle) GetReadySeq() uint64 {
	if x != nil {
		return x.ReadySeq
	}
	return 0
}

type Pull struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Generation    string                 `protobuf:"bytes,1,opt,name=generation,proto3" json:"generation,omitempty"`
	Seq           uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pull) Reset() {
	*x = Pull{}
	mi := &file_proto_sync_v1_sync_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pull) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pull) ProtoMessage() {}

func (x *Pull) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_v1_sync_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pull.ProtoReflect.Descriptor instead.
func (*Pull) Descriptor() ([]byte, []int) {
	return file_proto_sync_v1_sync_proto_rawDescGZIP(), []int{6}
}

func (x *Pull) GetGeneration() string {
	if x != nil {
		return x.Generation
	}
	return ""
}

func (x *Pull) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Generation    string                 `protobuf:"bytes,1,opt,name=generation,proto3" json:"generation,omitempty"`
	Seq           uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	MessageId     string                 `protobuf:"bytes,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_proto_sync_v1_sync_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_v1_sync_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_proto_sync_v1_sync_proto_rawDescGZIP(), []int{7}
}

func (x *Ack) GetGeneration() string {
	if x != nil {
		return x.Generation
	}
	return ""
}

func (x *Ack) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Ack) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

// Metrics contains one Prometheus text exposition snapshot. The server adds
// trusted syncer_id and component labels before forwarding it.
type Metrics struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	PrometheusText       []byte                 `protobuf:"bytes,1,opt,name=prometheus_text,json=prometheusText,proto3" json:"prometheus_text,omitempty"`
	CollectedAtUnixMilli int64                  `protobuf:"varint,2,opt,name=collected_at_unix_milli,json=collectedAtUnixMilli,proto3" json:"collected_at_unix_milli,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Metrics) Reset() {
	*x = Metrics{}
	mi := &file_proto_sync_v1_sync_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metrics) ProtoMessage() {}

func (x *Metrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_v1_sync_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metrics.ProtoReflect.Descriptor instead.
func (*Metrics) Descriptor() ([]byte, []int) {
	return file_proto_sync_v1_sync_proto_rawDescGZIP(), []int{8}
}

func (x *Metrics) GetPrometheusText() []byte {
	if x != nil {
		return x.PrometheusText
	}
	return nil
}

func (x *Metrics) GetCollectedAtUnixMilli() int64 {
	if x != nil {
		return x.CollectedAtUnixMilli
	}
	return 0
}

type ListSyncersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSyncersRequest) Reset() {
	*x = ListSyncersRequest{}
	mi := &file_proto_sync_v1_sync_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSyncersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSyncersRequest) ProtoMessage() {}

func (x *ListSyncersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_v1_sync_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSyncersRequest.ProtoReflect.Descriptor instead.
func (*ListSyncersRequest) Descriptor() ([]byte, []int) {
	return file_proto_sync_v1_sync_proto_rawDescGZIP(), []int{9}
}

type SyncerStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Connected     bool                   `protobuf:"varint,2,opt,name=connected,proto3" json:"connected,omitempty"`
	Generation    string                 `protobuf:"bytes,3,opt,name=generation,proto3" json:"generation,omitempty"`
	ReceivedSeq   uint64                 `protobuf:"varint,4,opt,name=received_seq,json=receivedSeq,proto3" json:"received_seq,omitempty"`
	AppliedSeq    uint64                 `protobuf:"varint,5,opt,name=applied_seq,json=appliedSeq,proto3" json:"applied_seq,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncerStatus) Reset() {
	*x = SyncerStatus{}
	mi := &file_proto_sync_v1_sync_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncerStatus) ProtoMessage() {}

func (x *SyncerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_v1_sync_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncerStatus.ProtoReflect.Descriptor instead.
func (*SyncerStatus) Descriptor() ([]byte, []int) {
	return file_proto_sync_v1_sync_proto_rawDescGZIP(), []int{10}
}

func (x *SyncerStatus) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SyncerStatus) GetConnected() bool {
	if x != nil {
		return x.Connected
	}
	return false
}

func (x *SyncerStatus) GetGeneration() string {
	if x != nil {
		return x.Generation
	}
	return ""
}

func (x *SyncerStatus) GetReceivedSeq() uint64 {
	if x != nil {
		return x.ReceivedSeq
	}
	return 0
}

func (x *SyncerStatus) GetAppliedSeq() uint64 {
	if x != nil {
		return x.AppliedSeq
	}
	return 0
}

func (x *SyncerStatus) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ListSyncersResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Syncers         []*SyncerStatus        `protobuf:"bytes,1,rep,name=syncers,proto3" json:"syncers,omitempty"`
	ConfigHash      string                 `protobuf:"bytes,2,opt,name=config_hash,json=configHash,proto3" json:"config_hash,omitempty"`
	LastReloadError string                 `protobuf:"bytes,3,opt,name=last_reload_error,json=lastReloadError,proto3" json:"last_reload_error,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListSyncersResponse) Reset() {
	*x = ListSyncersResponse{}
	mi := &file_proto_sync_v1_sync_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSyncersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSyncersResponse) ProtoMessage() {}

func (x *ListSyncersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_v1_sync_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSyncersResponse.ProtoReflect.Descriptor instead.
func (*ListSyncersResponse) Descriptor() ([]byte, []int) {
	return file_proto_sync_v1_sync_proto_rawDescGZIP(), []int{11}
}

func (x *ListSyncersResponse) GetSyncers() []*SyncerStatus {
	if x != nil {
		return x.Syncers
	}
	return nil
}

func (x *ListSyncersResponse) GetConfigHash() string {
	if x != nil {
		return x.ConfigHash
	}
	return ""
}

func (x *ListSyncersResponse) GetLastReloadError() string {
	if x != nil {
		return x.LastReloadError
	}
	return ""
}

type ReloadConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadConfigRequest) Reset() {
	*x = ReloadConfigRequest{}
	mi := &file_proto_sync_v1_sync_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadConfigRequest) ProtoMessage() {}

func (x *ReloadConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_v1_sync_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadConfigRequest.ProtoReflect.Descriptor instead.
func (*ReloadConfigRequest) Descriptor() ([]byte, []int) {
	return file_proto_sync_v1_sync_proto_rawDescGZIP(), []int{12}
}

type ReloadConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigHash    string                 `protobuf:"bytes,1,opt,name=config_hash,json=configHash,proto3" json:"config_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadConfigResponse) Reset() {
	*x = ReloadConfigResponse{}
	mi := &file_proto_sync_v1_sync_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadConfigResponse) ProtoMessage() {}

func (x *ReloadConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_v1_sync_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadConfigResponse.ProtoReflect.Descriptor instead.
func (*ReloadConfigResponse) Descriptor() ([]byte, []int) {
	return file_proto_sync_v1_sync_proto_rawDescGZIP(), []int{13}
}

func (x *ReloadConfigResponse) GetConfigHash() string {
	if x != nil {
		return x.ConfigHash
	}
	return ""
}

var File_proto_sync_v1_sync_proto protoreflect.FileDescriptor

const file_proto_sync_v1_sync_proto_rawDesc = "" +
	"\n" +
	"\x18proto/sync/v1/sync.proto\x12\tgosync.v1\"\x92\x02\n" +
	"\x0eCollectorFrame\x12(\n" +
	"\x05hello\x18\x01 \x01(\v2\x10.gosync.v1.HelloH\x00R\x05hello\x12(\n" +
	"\x05event\x18\x02 \x01(\v2\x10.gosync.v1.EventH\x00R\x05event\x12M\n" +
	"\x12replay_unavailable\x18\x03 \x01(\v2\x1c.gosync.v1.ReplayUnavailableH\x00R\x11replayUnavailable\x12.\n" +
	"\ametrics\x18\x04 \x01(\v2\x12.gosync.v1.MetricsH\x00R\ametrics\x12%\n" +
	"\x04idle\x18\x05 \x01(\v2\x0f.gosync.v1.IdleH\x00R\x04idleB\x06\n" +
	"\x04body\"`\n" +
	"\vServerFrame\x12%\n" +
	"\x04pull\x18\x01 \x01(\v2\x0f.gosync.v1.PullH\x00R\x04pull\x12\"\n" +
	"\x03ack\x18\x02 \x01(\v2\x0e.gosync.v1.AckH\x00R\x03ackB\x06\n" +
	"\x04body\"\xaf\x01\n" +
	"\x05Hello\x12\x1b\n" +
	"\tsyncer_id\x18\x01 \x01(\tR\bsyncerId\x12\x1e\n" +
	"\n" +
	"generation\x18\x02 \x01(\tR\n" +
	"generation\x12!\n" +
	"\fearliest_seq\x18\x03 \x01(\x04R\vearliestSeq\x12\x1b\n" +
	"\tready_seq\x18\x04 \x01(\x04R\breadySeq\x12)\n" +
	"\x10protocol_version\x18\x05 \x01(\tR\x0fprotocolVersion\"L\n" +
	"\x05Event\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12\x12\n" +
	"\x04json\x18\x03 \x01(\fR\x04json\"[\n" +
	"\x11ReplayUnavailable\x12#\n" +
	"\rrequested_seq\x18\x01 \x01(\x04R\frequestedSeq\x12!\n" +
	"\fearliest_seq\x18\x02 \x01(\x04R\vearliestSeq\"#\n" +
	"\x04Idle\x12\x1b\n" +
	"\tready_seq\x18\x01 \x01(\x04R\breadySeq\"8\n" +
	"\x04Pull\x12\x1e\n" +
	"\n" +
	"generation\x18\x01 \x01(\tR\n" +
	"generation\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\"V\n" +
	"\x03Ack\x12\x1e\n" +
	"\n" +
	"generation\x18\x01 \x01(\tR\n" +
	"generation\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\tR\tmessageId\"i\n" +
	"\aMetrics\x12'\n" +
	"\x0fprometheus_text\x18\x01 \x01(\fR\x0eprometheusText\x125\n" +
	"\x17collected_at_unix_milli\x18\x02 \x01(\x03R\x14collectedAtUnixMilli\"\x14\n" +
	"\x12ListSyncersRequest\"\xb6\x01\n" +
	"\fSyncerStatus\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\tconnected\x18\x02 \x01(\bR\tconnected\x12\x1e\n" +
	"\n" +
	"generation\x18\x03 \x01(\tR\n" +
	"generation\x12!\n" +
	"\freceived_seq\x18\x04 \x01(\x04R\vreceivedSeq\x12\x1f\n" +
	"\vapplied_seq\x18\x05 \x01(\x04R\n" +
	"appliedSeq\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"\x95\x01\n" +
	"\x13ListSyncersResponse\x121\n" +
	"\asyncers\x18\x01 \x03(\v2\x17.gosync.v1.SyncerStatusR\asyncers\x12\x1f\n" +
	"\vconfig_hash\x18\x02 \x01(\tR\n" +
	"configHash\x12*\n" +
	"\x11last_reload_error\x18\x03 \x01(\tR\x0flastReloadError\"\x15\n" +
	"\x13ReloadConfigRequest\"7\n" +
	"\x14ReloadConfigResponse\x12\x1f\n" +
	"\vconfig_hash\x18\x01 \x01(\tR\n" +
	"configHash2O\n" +
	"\vReplication\x12@\n" +
	"\aConnect\x12\x19.gosync.v1.CollectorFrame\x1a\x16.gosync.v1.ServerFrame(\x010\x012\xa6\x01\n" +
	"\x05Admin\x12L\n" +
	"\vListSyncers\x12\x1d.gosync.v1.ListSyncersRequest\x1a\x1e.gosync.v1.ListSyncersResponse\x12O\n" +
	"\fReloadConfig\x12\x1e.gosync.v1.ReloadConfigRequest\x1a\x1f.gosync.v1.ReloadConfigResponseB$Z\"go-sync/internal/rpc/syncv1;syncv1b\x06proto3"

var (
	file_proto_sync_v1_sync_proto_rawDescOnce sync.Once
	file_proto_sync_v1_sync_proto_rawDescData []byte
)

func file_proto_sync_v1_sync_proto_rawDescGZIP() []byte {
	file_proto_sync_v1_sync_proto_rawDescOnce.Do(func() {
		file_proto_sync_v1_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sync_v1_sync_proto_rawDesc), len(file_proto_sync_v1_sync_proto_rawDesc)))
	})
	return file_proto_sync_v1_sync_proto_rawDescData
}

var file_proto_sync_v1_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_sync_v1_sync_proto_goTypes = []any{
	(*CollectorFrame)(nil),       // 0: gosync.v1.CollectorFrame
	(*ServerFrame)(nil),          // 1: gosync.v1.ServerFrame
	(*Hello)(nil),                // 2: gosync.v1.Hello
	(*Event)(nil),                // 3: gosync.v1.Event
	(*ReplayUnavailable)(nil),    // 4: gosync.v1.ReplayUnavailable
	(*Idle)(nil),                 // 5: gosync.v1.Idle
	(*Pull)(nil),                 // 6: gosync.v1.Pull
	(*Ack)(nil),                  // 7: gosync.v1.Ack
	(*Metrics)(nil),              // 8: gosync.v1.Metrics
	(*ListSyncersRequest)(nil),   // 9: gosync.v1.ListSyncersRequest
	(*SyncerStatus)(nil),         // 10: gosync.v1.SyncerStatus
	(*ListSyncersResponse)(nil),  // 11: gosync.v1.ListSyncersResponse
	(*ReloadConfigRequest)(nil),  // 12: gosync.v1.ReloadConfigRequest
	(*ReloadConfigResponse)(nil), // 13: gosync.v1.ReloadConfigResponse
}
var file_proto_sync_v1_sync_proto_depIdxs = []int32{
	2,  // 0: gosync.v1.CollectorFrame.hello:type_name -> gosync.v1.Hello
	3,  // 1: gosync.v1.CollectorFrame.event:type_name -> gosync.v1.Event
	4,  // 2: gosync.v1.CollectorFrame.replay_unavailable:type_name -> gosync.v1.ReplayUnavailable
	8,  // 3: gosync.v1.CollectorFrame.metrics:type_name -> gosync.v1.Metrics
	5,  // 4: gosync.v1.CollectorFrame.idle:type_name -> gosync.v1.Idle
	6,  // 5: gosync.v1.ServerFrame.pull:type_name -> gosync.v1.Pull
	7,  // 6: gosync.v1.ServerFrame.ack:type_name -> gosync.v1.Ack
	10, // 7: gosync.v1.ListSyncersResponse.syncers:type_name -> gosync.v1.SyncerStatus
	0,  // 8: gosync.v1.Replication.Connect:input_type -> gosync.v1.CollectorFrame
	9,  // 9: gosync.v1.Admin.ListSyncers:input_type -> gosync.v1.ListSyncersRequest
	12, // 10: gosync.v1.Admin.ReloadConfig:input_type -> gosync.v1.ReloadConfigRequest
	1,  // 11: gosync.v1.Replication.Connect:output_type -> gosync.v1.ServerFrame
	11, // 12: gosync.v1.Admin.ListSyncers:output_type -> gosync.v1.ListSyncersResponse
	13, // 13: gosync.v1.Admin.ReloadConfig:output_type -> gosync.v1.ReloadConfigResponse
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_sync_v1_sync_proto_init() }
func file_proto_sync_v1_sync_proto_init() {
	if File_proto_sync_v1_sync_proto != nil {
		return
	}
	file_proto_sync_v1_sync_proto_msgTypes[0].OneofWrappers = []any{
		(*CollectorFrame_Hello)(nil),
		(*CollectorFrame_Event)(nil),
		(*CollectorFrame_ReplayUnavailable)(nil),
		(*CollectorFrame_Metrics)(nil),
		(*CollectorFrame_Idle)(nil),
	}
	file_proto_sync_v1_sync_proto_msgTypes[1].OneofWrappers = []any{
		(*ServerFrame_Pull)(nil),
		(*ServerFrame_Ack)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sync_v1_sync_proto_rawDesc), len(file_proto_sync_v1_sync_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_sync_v1_sync_proto_goTypes,
		DependencyIndexes: file_proto_sync_v1_sync_proto_depIdxs,
		MessageInfos:      file_proto_sync_v1_sync_proto_msgTypes,
	}.Build()
	File_proto_sync_v1_sync_proto = out.File
	file_proto_sync_v1_sync_proto_goTypes = nil
	file_proto_sync_v1_sync_proto_depIdxs = nil
}
